### ISSUE TITLE
This repro seems dead. I will try to maintain it

### ISSUE THREAD

**Issue by hegerdes** [kcp18/browserhistory#14]
Hi, 

this repro seems dead. I found it to be a nice little tool that should stay usable. I'm offering to maintain this tool with as much effort I can. I forked it and the first thing I did was to add ChromiumEdge support for Windows.

Unfortunately I don't own a Mac and haven't gotten to read about how to setup MacOS in a VM. But I will.
If your issues are still relevant please open them again at [hegerdes/browserhistory](https://github.com/hegerdes/browserhistory).

**Comment by sujanchegu** [comment]
Please checkout https://github.com/pesos/browser-history . The repo is properly maintained and is elegant in code structure.
