### ISSUE TITLE
Typo in variable name

### ISSUE THREAD

**Issue by ghost** [kcp18/browserhistory#2]
There's a typo in the naming of a dictionary in get_browserhistory() in browserhistory.py.

    # browserhistory is a dictionary that stores the query results based on the name of browsers.
    browserhistroy = {}

And later it is used again in lines 160-163.

        # put the query result based on the name of browsers.
        browserhistroy[browser] = query_result

    return browserhistroy

**Comment by kcp18** [comment]
Thank you, arron-seo. I didn't even notice that. I fixed it!
