### ISSUE TITLE
how to get chrome history in linux and windows

### ISSUE THREAD

**Issue by kannanrrk** [kcp18/browserhistory#4]

**Comment by kcp18** [comment]
For Linux, I haven't put the path for the Chrome. For windows, it should work if you installed the chrome in your computer. I will update the module this month. Do you have any suggestions?

**Comment by nehaj27** [comment]
how to download the history without closing the chrome window?

**Comment by kcp18** [comment]
you must close the chrome windows/program to extract the data because the data file is locked when the window is open.
